### ISSUE TITLE
Javascript p.register args NickName is safe?

### ISSUE THREAD

**Issue by kjyoffice** [bitwarden/passwordless-dotnet#104]
Hi,
First My devel stack is .NET But this question is client api... 
If this issue is Unmatched repo. guide to right repo please 😁

Question.
Javascript p.register args NickName is safe?
That's mean i understand set NickName is client only action. no server valid check....

i known... 
Bitwarden guys all security expert!
under my question is yours view baby level question... haha 😅

sample code.

```HTML
<input id="nickname" type="text" name="nickname" maxlength="50" />
<input type="button" value="Register Now" onclick="RegisterNow();" />
```

```Javascript
async function RegisterNow() {
  var nickName = document.getElementById('nickname').value;
  var p = new Passwordless.Client({ ... });

  // ...
  // Call my defined web api, get register token
  // - /GetRegisterToken.aspx
  // (** transfer with NickName to web api. but NickName is no response client)
  // Response JSON
  // { "statusCode" : "OK", "registerToken" : "..." ... }
  //var registerToken = resp.registerToken;
  // ...
  var regiResult = await p.register(registerToken, nickName);
  // ...
}
```

Make situation.
Bad guy NickName value write web attack code (ex, XSS)
use Chrome DevTools or ...

```Javascript
  //var regiResult = await p.register(registerToken, nickName);
  var nickName_BADGUY_REWRITE_VALUE_IS_BAD_CODE = '...';
  var regiResult = await p.register(registerToken, nickName_BADGUY_REWRITE_VALUE_IS_BAD_CODE);
}
```

After web app login using passkey.
go to my page get credentials list.

```HTTP
GET https://v4.passwordless.dev/credentials/list?userId=GUID HTTP/1.1
ApiSecret: ...
```

And response JSON in NickName value is safe?
or value is unsafe. but Bitwarden make scenario under safe.
that's mean credentials list is my account credentials.
other don't view this credentials.
register time, write bad nickname, and get credentials list response JSON bad NickName. self attack?

More question.
Nickname. passwordless.dev admin dashboard view list users time.
web browser display nickname is safe?

Please answer 😀
Thanks.

**Comment by abergs** [comment]
Hello @kjyoffice!
Thank you for your detailed question.

For all user input, I would recommend you to encode it properly depending on where you will render it, e.g. if you want to render it in HTML, you should HtmlEncode it. If you want to pass it as part of a URL, you need to UrlEncode it. If you want to make it part of a DB query you need to encode it properly or use whatever tools is offered, e.g. sql parameters.

We currently do not try to encode it to make itself for all these scenarios and we should make sure this is appropriately documented and perhaps add a default encoding.
